### ISSUE TITLE
import species information from FileMaker exported format

### ISSUE THREAD

**Issue by felipead87** [mfrasca/bauble.classic#47]
FIle Maker can export data in CSV format, attached is a small file as an example

**Comment by felipead87** [comment]
missing header...

the file looks like this.
"2012","","II","NATIVA","","","","ORCHIDACEAE","02/05/2012","Stenorrrhynchos","HIERBA","002012","","","ECUADOR","","","VIVO","ORCHIDOIDEAE","SPIRANTHINAE ","CRANICHIDEAE","IF-4B"
"2012","","II","NATIVA","","","","ORCHIDACEAE","02/05/2012","Stenorrrhynchos","HIERBA","002014","","","ECUADOR","","","VIVO","ORCHIDOIDEAE","SPIRANTHINAE ","CRANICHIDEAE","IF-4B"
"2012","","II","NATIVA","","","","ORCHIDACEAE","02/05/2012","Stenorrrhynchos","HIERBA","002015","","","ECUADOR","","","VIVO","ORCHIDOIDEAE","SPIRANTHINAE ","CRANICHIDEAE","IF-4B"
"2012","","II","NATIVA","","","","ORCHIDACEAE","02/05/2012","Stenorrrhynchos","HIERBA","002017","","","ECUADOR","","","VIVO","ORCHIDOIDEAE","SPIRANTHINAE ","CRANICHIDEAE","IF-4B"
"2012","","II","NATIVA","","","","ORCHIDACEAE","02/05/2012","Stenorrrhynchos","HIERBA","002019","","","ECUADOR","","","VIVO","ORCHIDOIDEAE","SPIRANTHINAE ","CRANICHIDEAE","IF-4B"
"2012","","II","NATIVA","","","","ORCHIDACEAE","02/05/2012","Stenorrrhynchos","HIERBA","002020","","","ECUADOR","","","VIVO","ORCHIDOIDEAE","SPIRANTHINAE ","CRANICHIDEAE","IF-4B"
"2012","","II","NATIVA","","","","ORCHIDACEAE","02/05/2012","Stenorrrhynchos","HIERBA","002021","","","ECUADOR","","","VIVO","ORCHIDOIDEAE","SPIRANTHINAE ","CRANICHIDEAE","IF-4B"
"2015","","II","NATIVA","","","","ORCHIDACEAE","20/01/2015","Stenorrrhynchos","HIERBA","015020","","","ECUADOR","","","VIVO","ORCHIDOIDEAE","SPIRANTHINAE ","CRANICHIDEAE","INV_COLEC"
"2012","","II","NATIVA","","","","ORCHIDACEAE","02/05/2012","Stenorrrhynchos","HIERBA","002023","","","ECUADOR","","","VIVO","ORCHIDOIDEAE","SPIRANTHINAE ","CRANICHIDEAE","IF-4B"

headers you can get from the xml export.
<?xml version="1.0" encoding="UTF-8" ?><FMPXMLRESULT xmlns="http://www.filemaker
.com/fmpxmlresult"><ERRORCODE>0</ERRORCODE><PRODUCT BUILD="02-04-2010" NAME="Fil
eMaker" VERSION="ProAdvanced 11.0v1"/><DATABASE DATEFORMAT="D/m/yyyy" LAYOUT=""
NAME="Base de Datos JBQ.fp7" RECORDS="7020" TIMEFORMAT="k:mm:ss "/><METADATA><FI
ELD EMPTYOK="YES" MAXREPEAT="1" NAME="A├▒o" TYPE="TEXT"/><FIELD EMPTYOK="YES" MA
XREPEAT="1" NAME="Autor" TYPE="TEXT"/><FIELD EMPTYOK="YES" MAXREPEAT="1" NAME="C
ITES" TYPE="TEXT"/><FIELD EMPTYOK="YES" MAXREPEAT="1" NAME="Condici├│n" TYPE="TE
XT"/><FIELD EMPTYOK="YES" MAXREPEAT="1" NAME="Conservaci├│n" TYPE="TEXT"/><FIELD
 EMPTYOK="YES" MAXREPEAT="1" NAME="Documento de ingreso" TYPE="TEXT"/><FIELD EMP
TYOK="YES" MAXREPEAT="1" NAME="Especie" TYPE="TEXT"/><FIELD EMPTYOK="YES" MAXREP
EAT="1" NAME="Familia" TYPE="TEXT"/><FIELD EMPTYOK="YES" MAXREPEAT="1" NAME="Fec
ha registro" TYPE="DATE"/><FIELD EMPTYOK="YES" MAXREPEAT="1" NAME="Genero" TYPE=
"TEXT"/><FIELD EMPTYOK="YES" MAXREPEAT="1" NAME="Habito" TYPE="TEXT"/><FIELD EMP
TYOK="YES" MAXREPEAT="1" NAME="Item" TYPE="TEXT"/><FIELD EMPTYOK="YES" MAXREPEAT
="1" NAME="N├║mero de Doc." TYPE="TEXT"/><FIELD EMPTYOK="YES" MAXREPEAT="1" NAME
="Observaciones" TYPE="TEXT"/><FIELD EMPTYOK="YES" MAXREPEAT="1" NAME="Pa├¡s" TY
PE="TEXT"/><FIELD EMPTYOK="YES" MAXREPEAT="1" NAME="Procedencia" TYPE="TEXT"/><F
IELD EMPTYOK="YES" MAXREPEAT="1" NAME="Provincia" TYPE="TEXT"/><FIELD EMPTYOK="Y
ES" MAXREPEAT="1" NAME="Situaci├│n" TYPE="TEXT"/><FIELD EMPTYOK="YES" MAXREPEAT=
"1" NAME="Subfamilia" TYPE="TEXT"/><FIELD EMPTYOK="YES" MAXREPEAT="1" NAME="Subt
ribu" TYPE="TEXT"/><FIELD EMPTYOK="YES" MAXREPEAT="1" NAME="Tribu" TYPE="TEXT"/>
<FIELD EMPTYOK="YES" MAXREPEAT="1" NAME="Ubicaci├│n" TYPE="TEXT"/></METADATA><RE
SULTSET FOUND="7020">

**Comment by mfrasca** [comment]
I'm looking at the example and I am writing down a doubt so I will remember asking:

the main purpose of this file is to to describe accessions? the example has in fact a 'Item' column which looks like a unique accession identifier, but the 'Especie' column is completely empty. Does it mean all these accessions have not been identified at rank 'species' but only at rank 'subtribe'?

**Comment by mfrasca** [comment]
fixing thoughts for tomorrow: a generic CSV importer is quite a bit more complicated than an object importer from, say, JSON or Python data.

the current importer under 'import->Comma Separated Values' works on data which has EXACTLY the same structure as the data in the database. for a generic CSV file, you would need map the fields in the flat file(s) being imported to table.column in the database.

on the other hand, when importing from object oriented data we can take advantage of SQLAlchemy's ORM and the code would probably look extremely linear.

**Comment by mfrasca** [comment]
I'm doing it a bit differently: rather than importing from the filemake format, I'm converting the filemaker export to the import format I've designed in #49

**Comment by mfrasca** [comment]
this is sort of working and a bit too generic to continue refer to it.

-how is the import from FileMaker working?
- there is an external script that extracts information from the FileMaker export and writes json files containing the same information.

-is the script part of Bauble?
- no, not really. I did not yet decide where to keep it. 
- probably it could go in a folder the JBQ and me are sharing, using `copy`.

-what is still missing in the translation-import from FileMaker?
- locations are not translated
- plants are not translated
- not all fields from accessions are translated

**Comment by mfrasca** [comment]
grouping fields according to object they describe:
Taxa: 
- Familia, Subfamilia, Tribu, Subtribu, Genero, Especie, 
- Autor, (of the lowest species)
- CITES, (NO, I, II)
- Conservación, (UICN: CR, DD, EN, LC, NT, PREOCUPACIÓN MENOR, VU)
- Condición, (cultivada, nativa, endémica, introducida, )
- Habito, 
- País, Provincia (si el país es Ecuador), 

Accession:
- Año, 
- Item, 
- Procedencia, (compra, colecta, in vitro, donación)
- Fecha registro, 
- Documento de ingreso, (factura)
- Número de Doc., 

Plant:
- Situación, (Viva-Muerta)
- Ubicación
- Observaciones

**Comment by mfrasca** [comment]
all the above stuff can easily be described in a config file, so that the conversion script can be written general enough as to fit in Bauble.
